/* 
 * Known Pose API
 *
 * Define and retrieve (accurate) semantic poses in a 2D environment. This version is a workaround for some not yet available features of the OpenAPI Specification v3.0 (e.g. `anyOf` as a response type and adding a  `discriminator` for supporting polymorphism/composition). Therefore, ATM the sub-components BasicPose and InaccuratePose are reference objects inside their respective parent model.  
 *
 * OpenAPI spec version: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccuratePoseArray
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccuratePoseArrayTests
    {
        // TODO uncomment below to declare an instance variable for AccuratePoseArray
        //private AccuratePoseArray instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccuratePoseArray
            //instance = new AccuratePoseArray();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccuratePoseArray
        /// </summary>
        [Test]
        public void AccuratePoseArrayInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccuratePoseArray
            //Assert.IsInstanceOfType<AccuratePoseArray> (instance, "variable 'instance' is a AccuratePoseArray");
        }


        /// <summary>
        /// Test the property 'PoseArray'
        /// </summary>
        [Test]
        public void PoseArrayTest()
        {
            // TODO unit test for the property 'PoseArray'
        }

    }

}
