# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from known_pose_service.models.base_model_ import Model
from known_pose_service.models.inaccurate_pose import InaccuratePose  # noqa: F401,E501
from known_pose_service import util


class InaccuratePoseArray(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pose_array: List[InaccuratePose]=None):  # noqa: E501
        """InaccuratePoseArray - a model defined in Swagger

        :param pose_array: The pose_array of this InaccuratePoseArray.  # noqa: E501
        :type pose_array: List[InaccuratePose]
        """
        self.swagger_types = {
            'pose_array': List[InaccuratePose]
        }

        self.attribute_map = {
            'pose_array': 'pose_array'
        }
        self._pose_array = pose_array

    @classmethod
    def from_dict(cls, dikt) -> 'InaccuratePoseArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InaccuratePoseArray of this InaccuratePoseArray.  # noqa: E501
        :rtype: InaccuratePoseArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pose_array(self) -> List[InaccuratePose]:
        """Gets the pose_array of this InaccuratePoseArray.


        :return: The pose_array of this InaccuratePoseArray.
        :rtype: List[InaccuratePose]
        """
        return self._pose_array

    @pose_array.setter
    def pose_array(self, pose_array: List[InaccuratePose]):
        """Sets the pose_array of this InaccuratePoseArray.


        :param pose_array: The pose_array of this InaccuratePoseArray.
        :type pose_array: List[InaccuratePose]
        """
        if pose_array is None:
            raise ValueError("Invalid value for `pose_array`, must not be `None`")  # noqa: E501

        self._pose_array = pose_array
