# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from known_pose_service.models.base_model_ import Model
from known_pose_service import util


class Orientation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, x: float=None, y: float=None, z: float=None, w: float=None):  # noqa: E501
        """Orientation - a model defined in Swagger

        :param x: The x of this Orientation.  # noqa: E501
        :type x: float
        :param y: The y of this Orientation.  # noqa: E501
        :type y: float
        :param z: The z of this Orientation.  # noqa: E501
        :type z: float
        :param w: The w of this Orientation.  # noqa: E501
        :type w: float
        """
        self.swagger_types = {
            'x': float,
            'y': float,
            'z': float,
            'w': float
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y',
            'z': 'z',
            'w': 'w'
        }
        self._x = x
        self._y = y
        self._z = z
        self._w = w

    @classmethod
    def from_dict(cls, dikt) -> 'Orientation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Orientation of this Orientation.  # noqa: E501
        :rtype: Orientation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> float:
        """Gets the x of this Orientation.


        :return: The x of this Orientation.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x: float):
        """Sets the x of this Orientation.


        :param x: The x of this Orientation.
        :type x: float
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self) -> float:
        """Gets the y of this Orientation.


        :return: The y of this Orientation.
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y: float):
        """Sets the y of this Orientation.


        :param y: The y of this Orientation.
        :type y: float
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y

    @property
    def z(self) -> float:
        """Gets the z of this Orientation.


        :return: The z of this Orientation.
        :rtype: float
        """
        return self._z

    @z.setter
    def z(self, z: float):
        """Sets the z of this Orientation.


        :param z: The z of this Orientation.
        :type z: float
        """
        if z is None:
            raise ValueError("Invalid value for `z`, must not be `None`")  # noqa: E501

        self._z = z

    @property
    def w(self) -> float:
        """Gets the w of this Orientation.


        :return: The w of this Orientation.
        :rtype: float
        """
        return self._w

    @w.setter
    def w(self, w: float):
        """Sets the w of this Orientation.


        :param w: The w of this Orientation.
        :type w: float
        """
        if w is None:
            raise ValueError("Invalid value for `w`, must not be `None`")  # noqa: E501

        self._w = w
