# coding: utf-8

"""
    Known Pose API

    Define and retrieve (accurate) semantic poses in a 2D environment. This version is a workaround for some not yet available features of the OpenAPI Specification v3.0 (e.g. `anyOf` as a response type and adding a  `discriminator` for supporting polymorphism/composition). Therefore, ATM the sub-components BasicPose and InaccuratePose are reference objects inside their respective parent model.    # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: Kai.Waelti@dfki.de
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import known_pose_client
from known_pose_client.api.developers_api import DevelopersApi  # noqa: E501
from known_pose_client.rest import ApiException


class TestDevelopersApi(unittest.TestCase):
    """DevelopersApi unit test stubs"""

    def setUp(self):
        self.api = known_pose_client.api.developers_api.DevelopersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_pose(self):
        """Test case for add_pose

        adds a pose item  # noqa: E501
        """
        pass

    def test_poses_id_delete(self):
        """Test case for poses_id_delete

        deletes a pose item  # noqa: E501
        """
        pass

    def test_search_accurate_pose(self):
        """Test case for search_accurate_pose

        searches accurate pose  # noqa: E501
        """
        pass

    def test_search_pose(self):
        """Test case for search_pose

        searches pose  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
