/**
 * Known Pose API
 * Define and retrieve (accurate) semantic poses in a 2D environment. This version is a workaround for some not yet available features of the OpenAPI Specification v3.0 (e.g. `anyOf` as a response type and adding a  `discriminator` for supporting polymorphism/composition). Therefore, ATM the sub-components BasicPose and InaccuratePose are reference objects inside their respective parent model.  
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccuratePose from './AccuratePose';

/**
 * The AccuratePoseArray model module.
 * @module model/AccuratePoseArray
 * @version 1.1.10
 */
class AccuratePoseArray {
    /**
     * Constructs a new <code>AccuratePoseArray</code>.
     * Array containing matching accurate poses
     * @alias module:model/AccuratePoseArray
     * @param poseArray {Array.<module:model/AccuratePose>} 
     */
    constructor(poseArray) { 
        
        AccuratePoseArray.initialize(this, poseArray);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, poseArray) { 
        obj['pose_array'] = poseArray;
    }

    /**
     * Constructs a <code>AccuratePoseArray</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccuratePoseArray} obj Optional instance to populate.
     * @return {module:model/AccuratePoseArray} The populated <code>AccuratePoseArray</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccuratePoseArray();

            if (data.hasOwnProperty('pose_array')) {
                obj['pose_array'] = ApiClient.convertToType(data['pose_array'], [AccuratePose]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/AccuratePose>} pose_array
 */
AccuratePoseArray.prototype['pose_array'] = undefined;






export default AccuratePoseArray;

