/* 
 * Known Pose API
 *
 * Define and retrieve (accurate) semantic poses in a 2D environment.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using KnownPose.Api;
using KnownPose.Model;
using KnownPose.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace KnownPose.Test
{
    /// <summary>
    ///  Class for testing AccuratePose
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccuratePoseTests
    {
        // TODO uncomment below to declare an instance variable for AccuratePose
        //private AccuratePose instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccuratePose
            //instance = new AccuratePose();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccuratePose
        /// </summary>
        [Test]
        public void AccuratePoseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AccuratePose
            //Assert.IsInstanceOf(typeof(AccuratePose), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Orientation'
        /// </summary>
        [Test]
        public void OrientationTest()
        {
            // TODO unit test for the property 'Orientation'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TakenAt'
        /// </summary>
        [Test]
        public void TakenAtTest()
        {
            // TODO unit test for the property 'TakenAt'
        }
        /// <summary>
        /// Test the property 'ReferenceScan'
        /// </summary>
        [Test]
        public void ReferenceScanTest()
        {
            // TODO unit test for the property 'ReferenceScan'
        }

    }

}
