/* 
 * Known Pose API
 *
 * Get and set (accurate) semantic poses for an environment.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using KnownPose.Api;
using KnownPose.Model;
using KnownPose.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace KnownPose.Test
{
    /// <summary>
    ///  Class for testing Orientation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrientationTests
    {
        // TODO uncomment below to declare an instance variable for Orientation
        //private Orientation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Orientation
            //instance = new Orientation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Orientation
        /// </summary>
        [Test]
        public void OrientationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Orientation
            //Assert.IsInstanceOf(typeof(Orientation), instance);
        }


        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Test]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }
        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Test]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }
        /// <summary>
        /// Test the property 'Z'
        /// </summary>
        [Test]
        public void ZTest()
        {
            // TODO unit test for the property 'Z'
        }
        /// <summary>
        /// Test the property 'W'
        /// </summary>
        [Test]
        public void WTest()
        {
            // TODO unit test for the property 'W'
        }

    }

}
