# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inaccurate_pose import InaccuratePose  # noqa: F401,E501
from swagger_server import util


class AccuratePose(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, taken_at: datetime=None, reference_scan: str=None):  # noqa: E501
        """AccuratePose - a model defined in Swagger

        :param id: The id of this AccuratePose.  # noqa: E501
        :type id: str
        :param taken_at: The taken_at of this AccuratePose.  # noqa: E501
        :type taken_at: datetime
        :param reference_scan: The reference_scan of this AccuratePose.  # noqa: E501
        :type reference_scan: str
        """
        self.swagger_types = {
            'id': str,
            'taken_at': datetime,
            'reference_scan': str
        }

        self.attribute_map = {
            'id': 'id',
            'taken_at': 'taken_at',
            'reference_scan': 'reference_scan'
        }
        self._id = id
        self._taken_at = taken_at
        self._reference_scan = reference_scan

    @classmethod
    def from_dict(cls, dikt) -> 'AccuratePose':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccuratePose of this AccuratePose.  # noqa: E501
        :rtype: AccuratePose
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this AccuratePose.


        :return: The id of this AccuratePose.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this AccuratePose.


        :param id: The id of this AccuratePose.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def taken_at(self) -> datetime:
        """Gets the taken_at of this AccuratePose.


        :return: The taken_at of this AccuratePose.
        :rtype: datetime
        """
        return self._taken_at

    @taken_at.setter
    def taken_at(self, taken_at: datetime):
        """Sets the taken_at of this AccuratePose.


        :param taken_at: The taken_at of this AccuratePose.
        :type taken_at: datetime
        """
        if taken_at is None:
            raise ValueError("Invalid value for `taken_at`, must not be `None`")  # noqa: E501

        self._taken_at = taken_at

    @property
    def reference_scan(self) -> str:
        """Gets the reference_scan of this AccuratePose.

        Contents of the reference scan assembled as point cloud data following [RFC 4648 § 5](https://tools.ietf.org/html/rfc4648#section-5)  # noqa: E501

        :return: The reference_scan of this AccuratePose.
        :rtype: str
        """
        return self._reference_scan

    @reference_scan.setter
    def reference_scan(self, reference_scan: str):
        """Sets the reference_scan of this AccuratePose.

        Contents of the reference scan assembled as point cloud data following [RFC 4648 § 5](https://tools.ietf.org/html/rfc4648#section-5)  # noqa: E501

        :param reference_scan: The reference_scan of this AccuratePose.
        :type reference_scan: str
        """
        if reference_scan is None:
            raise ValueError("Invalid value for `reference_scan`, must not be `None`")  # noqa: E501

        self._reference_scan = reference_scan
