# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.orientation import Orientation  # noqa: F401,E501
from swagger_server.models.position import Position  # noqa: F401,E501
from swagger_server import util


class BasicPose(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, position: Position=None, orientation: Orientation=None):  # noqa: E501
        """BasicPose - a model defined in Swagger

        :param name: The name of this BasicPose.  # noqa: E501
        :type name: str
        :param position: The position of this BasicPose.  # noqa: E501
        :type position: Position
        :param orientation: The orientation of this BasicPose.  # noqa: E501
        :type orientation: Orientation
        """
        self.swagger_types = {
            'name': str,
            'position': Position,
            'orientation': Orientation
        }

        self.attribute_map = {
            'name': 'name',
            'position': 'position',
            'orientation': 'orientation'
        }
        self._name = name
        self._position = position
        self._orientation = orientation

    @classmethod
    def from_dict(cls, dikt) -> 'BasicPose':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BasicPose of this BasicPose.  # noqa: E501
        :rtype: BasicPose
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this BasicPose.


        :return: The name of this BasicPose.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BasicPose.


        :param name: The name of this BasicPose.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def position(self) -> Position:
        """Gets the position of this BasicPose.


        :return: The position of this BasicPose.
        :rtype: Position
        """
        return self._position

    @position.setter
    def position(self, position: Position):
        """Sets the position of this BasicPose.


        :param position: The position of this BasicPose.
        :type position: Position
        """
        if position is None:
            raise ValueError("Invalid value for `position`, must not be `None`")  # noqa: E501

        self._position = position

    @property
    def orientation(self) -> Orientation:
        """Gets the orientation of this BasicPose.


        :return: The orientation of this BasicPose.
        :rtype: Orientation
        """
        return self._orientation

    @orientation.setter
    def orientation(self, orientation: Orientation):
        """Sets the orientation of this BasicPose.


        :param orientation: The orientation of this BasicPose.
        :type orientation: Orientation
        """
        if orientation is None:
            raise ValueError("Invalid value for `orientation`, must not be `None`")  # noqa: E501

        self._orientation = orientation
