# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.basic_pose import BasicPose  # noqa: F401,E501
from swagger_server.models.orientation import Orientation  # noqa: F401,E501
from swagger_server.models.position import Position  # noqa: F401,E501
from swagger_server import util


class InaccuratePose(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, position: Position=None, orientation: Orientation=None, id: str=None, taken_at: datetime=None):  # noqa: E501
        """InaccuratePose - a model defined in Swagger

        :param name: The name of this InaccuratePose.  # noqa: E501
        :type name: str
        :param position: The position of this InaccuratePose.  # noqa: E501
        :type position: Position
        :param orientation: The orientation of this InaccuratePose.  # noqa: E501
        :type orientation: Orientation
        :param id: The id of this InaccuratePose.  # noqa: E501
        :type id: str
        :param taken_at: The taken_at of this InaccuratePose.  # noqa: E501
        :type taken_at: datetime
        """
        self.swagger_types = {
            'name': str,
            'position': Position,
            'orientation': Orientation,
            'id': str,
            'taken_at': datetime
        }

        self.attribute_map = {
            'name': 'name',
            'position': 'position',
            'orientation': 'orientation',
            'id': 'id',
            'taken_at': 'taken_at'
        }
        self._name = name
        self._position = position
        self._orientation = orientation
        self._id = id
        self._taken_at = taken_at

    @classmethod
    def from_dict(cls, dikt) -> 'InaccuratePose':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InaccuratePose of this InaccuratePose.  # noqa: E501
        :rtype: InaccuratePose
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InaccuratePose.


        :return: The name of this InaccuratePose.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InaccuratePose.


        :param name: The name of this InaccuratePose.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def position(self) -> Position:
        """Gets the position of this InaccuratePose.


        :return: The position of this InaccuratePose.
        :rtype: Position
        """
        return self._position

    @position.setter
    def position(self, position: Position):
        """Sets the position of this InaccuratePose.


        :param position: The position of this InaccuratePose.
        :type position: Position
        """
        if position is None:
            raise ValueError("Invalid value for `position`, must not be `None`")  # noqa: E501

        self._position = position

    @property
    def orientation(self) -> Orientation:
        """Gets the orientation of this InaccuratePose.


        :return: The orientation of this InaccuratePose.
        :rtype: Orientation
        """
        return self._orientation

    @orientation.setter
    def orientation(self, orientation: Orientation):
        """Sets the orientation of this InaccuratePose.


        :param orientation: The orientation of this InaccuratePose.
        :type orientation: Orientation
        """
        if orientation is None:
            raise ValueError("Invalid value for `orientation`, must not be `None`")  # noqa: E501

        self._orientation = orientation

    @property
    def id(self) -> str:
        """Gets the id of this InaccuratePose.


        :return: The id of this InaccuratePose.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this InaccuratePose.


        :param id: The id of this InaccuratePose.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def taken_at(self) -> datetime:
        """Gets the taken_at of this InaccuratePose.


        :return: The taken_at of this InaccuratePose.
        :rtype: datetime
        """
        return self._taken_at

    @taken_at.setter
    def taken_at(self, taken_at: datetime):
        """Sets the taken_at of this InaccuratePose.


        :param taken_at: The taken_at of this InaccuratePose.
        :type taken_at: datetime
        """
        if taken_at is None:
            raise ValueError("Invalid value for `taken_at`, must not be `None`")  # noqa: E501

        self._taken_at = taken_at
