/**
 * Known Pose API
 * Define and retrieve (accurate) semantic poses in a 2D environment. This version is a workaround for some not yet available features of the OpenAPI Specification v3.0 (e.g. `anyOf` as a response type and adding a  `discriminator` for supporting polymorphism/composition). Therefore, ATM the sub-components BasicPose and InaccuratePose are reference objects inside their respective parent model.  
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KnownPoseClient);
  }
}(this, function(expect, KnownPoseClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KnownPoseClient.DevelopersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DevelopersApi', function() {
    describe('addAccuratePose', function() {
      it('should call addAccuratePose successfully', function(done) {
        //uncomment below and update the code to test addAccuratePose
        //instance.addAccuratePose(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addInaccuratePose', function() {
      it('should call addInaccuratePose successfully', function(done) {
        //uncomment below and update the code to test addInaccuratePose
        //instance.addInaccuratePose(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('posesIdDelete', function() {
      it('should call posesIdDelete successfully', function(done) {
        //uncomment below and update the code to test posesIdDelete
        //instance.posesIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchAccuratePose', function() {
      it('should call searchAccuratePose successfully', function(done) {
        //uncomment below and update the code to test searchAccuratePose
        //instance.searchAccuratePose(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchPose', function() {
      it('should call searchPose successfully', function(done) {
        //uncomment below and update the code to test searchPose
        //instance.searchPose(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
