/* 
 * Known Pose API
 *
 * Define and retrieve (accurate) semantic poses in a 2D environment.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = KnownPose.Client.OpenAPIDateConverter;

namespace KnownPose.Model
{
    /// <summary>
    /// AccuratePoseAllOf
    /// </summary>
    [DataContract]
    public partial class AccuratePoseAllOf :  IEquatable<AccuratePoseAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccuratePoseAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccuratePoseAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccuratePoseAllOf" /> class.
        /// </summary>
        /// <param name="referenceScan">Contents of the reference scan assembled as point cloud data following [RFC 4648 § 5](https://tools.ietf.org/html/rfc4648#section-5) (required).</param>
        public AccuratePoseAllOf(string referenceScan = default(string))
        {
            // to ensure "referenceScan" is required (not null)
            if (referenceScan == null)
            {
                throw new InvalidDataException("referenceScan is a required property for AccuratePoseAllOf and cannot be null");
            }
            else
            {
                this.ReferenceScan = referenceScan;
            }
            
        }
        
        /// <summary>
        /// Contents of the reference scan assembled as point cloud data following [RFC 4648 § 5](https://tools.ietf.org/html/rfc4648#section-5)
        /// </summary>
        /// <value>Contents of the reference scan assembled as point cloud data following [RFC 4648 § 5](https://tools.ietf.org/html/rfc4648#section-5)</value>
        [DataMember(Name="reference_scan", EmitDefaultValue=false)]
        public string ReferenceScan { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AccuratePoseAllOf {\n");
            sb.Append("  ReferenceScan: ").Append(ReferenceScan).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AccuratePoseAllOf);
        }

        /// <summary>
        /// Returns true if AccuratePoseAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of AccuratePoseAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccuratePoseAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ReferenceScan == input.ReferenceScan ||
                    (this.ReferenceScan != null &&
                    this.ReferenceScan.Equals(input.ReferenceScan))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReferenceScan != null)
                    hashCode = hashCode * 59 + this.ReferenceScan.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
