/**
 * Known Pose API
 * Define and retrieve (accurate) semantic poses in a 2D environment. This version is a workaround for some not yet available features of the OpenAPI Specification v3.0 (e.g. `anyOf` as a response type and adding a  `discriminator` for supporting polymorphism/composition). Therefore, ATM the sub-components BasicPose and InaccuratePose are reference objects inside their respective parent model.  
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccuratePose } from './accuratePose';

/**
* Array containing matching accurate poses
*/
export class AccuratePoseArray {
    'poseArray': Array<AccuratePose>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "poseArray",
            "baseName": "pose_array",
            "type": "Array<AccuratePose>"
        }    ];

    static getAttributeTypeMap() {
        return AccuratePoseArray.attributeTypeMap;
    }
}

