/* 
 * Known Pose API
 *
 * Get and set (accurate) semantic poses for an environment.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using KnownPoses.Api;
using KnownPoses.Model;
using KnownPoses.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace KnownPoses.Test
{
    /// <summary>
    ///  Class for testing AccuratePoseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccuratePoseAllOfTests
    {
        // TODO uncomment below to declare an instance variable for AccuratePoseAllOf
        //private AccuratePoseAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccuratePoseAllOf
            //instance = new AccuratePoseAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccuratePoseAllOf
        /// </summary>
        [Test]
        public void AccuratePoseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AccuratePoseAllOf
            //Assert.IsInstanceOf(typeof(AccuratePoseAllOf), instance);
        }


        /// <summary>
        /// Test the property 'ReferenceScan'
        /// </summary>
        [Test]
        public void ReferenceScanTest()
        {
            // TODO unit test for the property 'ReferenceScan'
        }

    }

}
