/* 
 * Known Pose API
 *
 * Get and set (accurate) semantic poses for an environment.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using KnownPoses.Api;
using KnownPoses.Model;
using KnownPoses.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace KnownPoses.Test
{
    /// <summary>
    ///  Class for testing InaccuratePose
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InaccuratePoseTests
    {
        // TODO uncomment below to declare an instance variable for InaccuratePose
        //private InaccuratePose instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InaccuratePose
            //instance = new InaccuratePose();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InaccuratePose
        /// </summary>
        [Test]
        public void InaccuratePoseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InaccuratePose
            //Assert.IsInstanceOf(typeof(InaccuratePose), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Orientation'
        /// </summary>
        [Test]
        public void OrientationTest()
        {
            // TODO unit test for the property 'Orientation'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TakenAt'
        /// </summary>
        [Test]
        public void TakenAtTest()
        {
            // TODO unit test for the property 'TakenAt'
        }

    }

}
