/* 
 * Known Pose API
 *
 * Get and set (accurate) semantic poses for an environment.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using KnownPoses.Api;
using KnownPoses.Model;
using KnownPoses.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace KnownPoses.Test
{
    /// <summary>
    ///  Class for testing InaccuratePoseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InaccuratePoseAllOfTests
    {
        // TODO uncomment below to declare an instance variable for InaccuratePoseAllOf
        //private InaccuratePoseAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InaccuratePoseAllOf
            //instance = new InaccuratePoseAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InaccuratePoseAllOf
        /// </summary>
        [Test]
        public void InaccuratePoseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InaccuratePoseAllOf
            //Assert.IsInstanceOf(typeof(InaccuratePoseAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TakenAt'
        /// </summary>
        [Test]
        public void TakenAtTest()
        {
            // TODO unit test for the property 'TakenAt'
        }

    }

}
