/**
 * Known Pose API
 * Define and retrieve (accurate) semantic poses in a 2D environment.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: Kai.Waelti@dfki.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse200 { 
    id: string;
    deleted: boolean;
}