/* 
 * Known Pose API
 *
 * Define and retrieve (accurate) semantic poses in a 2D environment. This version is a workaround for some not yet available features of the OpenAPI Specification v3.0 (e.g. `anyOf` as a response type and adding a  `discriminator` for supporting polymorphism/composition). Therefore, ATM the sub-components BasicPose and InaccuratePose are reference objects inside their respective parent model.  
 *
 * OpenAPI spec version: 1.1.0
 * Contact: Kai.Waelti@dfki.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DevelopersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DevelopersApiTests
    {
        private DevelopersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DevelopersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DevelopersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DevelopersApi
            //Assert.IsInstanceOfType(typeof(DevelopersApi), instance, "instance is a DevelopersApi");
        }

        /// <summary>
        /// Test AddPose
        /// </summary>
        [Test]
        public void AddPoseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BasicPose body = null;
            //instance.AddPose(body);
            
        }
        /// <summary>
        /// Test PosesIdDelete
        /// </summary>
        [Test]
        public void PosesIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.PosesIdDelete(id);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        /// <summary>
        /// Test SearchAccuratePose
        /// </summary>
        [Test]
        public void SearchAccuratePoseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string searchString = null;
            //int? skip = null;
            //int? limit = null;
            //var response = instance.SearchAccuratePose(id, searchString, skip, limit);
            //Assert.IsInstanceOf<AccuratePoseArray> (response, "response is AccuratePoseArray");
        }
        /// <summary>
        /// Test SearchPose
        /// </summary>
        [Test]
        public void SearchPoseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string searchString = null;
            //int? skip = null;
            //int? limit = null;
            //var response = instance.SearchPose(id, searchString, skip, limit);
            //Assert.IsInstanceOf<InaccuratePoseArray> (response, "response is InaccuratePoseArray");
        }
    }

}
