# coding: utf-8

"""
    Known Pose API

    Get and set (accurate) semantic poses for an environment.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: Kai.Waelti@dfki.de
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import known_pose
from known_pose.api.developers_api import DevelopersApi  # noqa: E501
from known_pose.rest import ApiException


class TestDevelopersApi(unittest.TestCase):
    """DevelopersApi unit test stubs"""

    def setUp(self):
        self.api = known_pose.api.developers_api.DevelopersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_pose(self):
        """Test case for add_pose

        adds a pose item  # noqa: E501
        """
        pass

    def test_search_pose(self):
        """Test case for search_pose

        searches pose  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
