# coding: utf-8

"""
    Known Pose API

    Get and set (accurate) semantic poses for an environment.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: Kai.Waelti@dfki.de
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import known_poses
from known_poses.models.orientation import Orientation  # noqa: E501
from known_poses.rest import ApiException


class TestOrientation(unittest.TestCase):
    """Orientation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrientation(self):
        """Test Orientation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = known_poses.models.orientation.Orientation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
